name: Linux User Management Autograding

on:
  push:
  pull_request:

jobs:
  grade:
    name: Run Autograder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required files
        run: |
          test -f README.md
          test -f starter.sh
          test -f test.sh

      - name: Make test executable
        run: chmod +x test.sh

      - name: Run autograder
        run: sudo ./test.sh
